// src/components/Navigation.svelte
<style>

</style>

<header>
  <nav>
    <ul>
      <li>
        <a href="#welcome">Steve Frenzel - Web Developer</a>
      </li>
      <li>
        <a href="#about">About</a>
      </li>
      <li>
        <a href="#services">Services</a>
      </li>
      <li>
        <a href="#contact">Contact</a>
      </li>
    </ul>
  </nav>
</header>

// components/Navigation.jsx
export default function Navigation() {
  return (
    <header>
      <nav>
        <ul>
          <li>
            <a href='#welcome'>Steve Frenzel</a>
          </li>
          <li>
            <a href='#about'>About</a>
          </li>
          <li>
            <a href='#services'>Services</a>
          </li>
          <li>
            <a href='#references'>References</a>
          </li>
          <li>
            <a href='#contact'>Contact</a>
          </li>
        </ul>
      </nav>
    </header>
  );
}
