// src/components/Services.svelte
<section id="services">
  <h2>Services</h2>
  <p>
    First meeting to discuss the scope and cost of the project, either in person
    or via video call.
    <em>(Free of charge!)</em>
  </p>
  <p>
    Creating an interactive prototype of the website or app with
    <mark>Sketch</mark>
    .
  </p>
  <p>
    Building it with
    <mark>Accessibility</mark>
    ,
    <mark>Best Practices</mark>
    ,
    <mark>Performance</mark>
    and
    <mark>SEO</mark>
    in mind. Measurement and optimisation with
    <mark>Google Lighthouse</mark>
    and other tools.
  </p>
  <p>
    Optional: Maintaining the project for a monthly fee. Prices depend on the
    size of the project and duration of support.
  </p>

</section>

// components/Services.jsx
export default function Services() {
  return (
    <section id='services'>
      <h2>Services</h2>
      <h3>1. First meeting and planning</h3>
      <p>
        Meeting in person or via video call to{' '}
        <mark>get to know each other</mark> and discuss the scope and cost of
        the project. (Free of charge!)
      </p>
      <h3>2. Creating a draft</h3>
      <p>
        Developing an <mark>interactive design of the project</mark>. Either as
        design in Sketch or live (and private) on Netlify.
      </p>
      <h3>3. Building the project</h3>
      <p>
        Developing your website (or app) with{' '}
        <mark>Accessibility, Best Practices, Performance and SEO</mark> in mind.
        To measure these values, I use Google Lighthouse, among others.
      </p>
      <h3>4. Maintenance</h3>
      <p>
        If desired, I can <mark>maintain the project</mark> for a monthly fee.
        Prices depend on the size of it and duration of support.
      </p>
    </section>
  );
}
