// components/About.jsx
export default function About() {
  return (
    <section id='about'>
      <h2>About me</h2>
      <p>
        I am not a web developer. At least I was not always. I also have over 10
        years experience in the music business as a sound engineer, producer and
        stagehand. Thanks to this time I learned a lot about people and how to
        work with them. I have also learned to plan large and small projects of
        all kinds, to execute them carefully and implement them successfully.
      </p>
      <p>
        Translating your vision to your customers (or visitors) is my main goal.
        In order to achieve this, I constantly educate myself to be able to
        decide which technology will best fit your project.The result will be an
        intuitive, performant and easily accessible product, taking current
        development best practices into account.
      </p>
    </section>
  );
}

// src/components/About.svelte
<style>
  /* section {
    width: 100vw;
    height: 100vh;
    background-color: lightcoral;
  } */
</style>

<section id="about">
  <h2>About me</h2>
  <p>
    I’ve worked for a number of exciting startups and established companies. My
    main goal is to
    <mark>translate your vision</mark>
    to your customers or visitors. In order to achieve this, I constantly
    educate myself to be able to decide
    <mark>which technology will best fit</mark>
    your project.
  </p>
  <p>
    First of all I would like to
    <mark>get to know you</mark>
    in order to give your idea a form. Based on this, I will develop an
    <mark>interactive design of the website (or app)</mark>
    together with you, which will serve as the foundation for the final product.
  </p>
  <p>
    The result will be an
    <mark>intuitive</mark>
    ,
    <mark>performant</mark>
    and easily
    <mark>accessible</mark>
    product, taking current development best practices into account.
  </p>
</section>
