// components/Contact.jsx
export default function Contact() {
  return (
    <section id='contact'>
      <h2>Contact</h2>
      <img
        src='/illustrations/inbox-cleanup.svg'
        alt='Ticked off letter inside envelope'
      />
      <p>
        <a href='mailto:stevefrenzel@gmx.de?subject=Enquiry about website or app'>
          Click here to send me an e-mail{' '}
        </a>
        or fill out the form below:
      </p>
      <form
        name='contact'
        method='post'
        action='/success'
        data-netlify='true'
        netlify-honeypot='bot-field'
      >
        {/* For Netlify: */}
        <input type='hidden' name='form-name' value='contact' />
        <label htmlFor='first-name'>First name:</label>
        <input
          className='contact-input'
          type='text'
          name='first-name'
          id='first-name'
          placeholder='First name'
          required
        ></input>
        <label htmlFor='last-name'>Last name:</label>
        <input
          className='contact-input'
          type='text'
          name='last-name'
          id='last-name'
          placeholder='Last name'
          required
        ></input>
        <label htmlFor='e-mail'>E-Mail:</label>
        <input
          className='contact-input'
          type='email'
          name='e-mail'
          id='e-mail'
          placeholder='Last name'
          required
        ></input>
        <label htmlFor='enquiry'>Enquiry:</label>
        <textarea
          className='contact-input'
          id='enquiry'
          name='enquiry'
          rows='5'
          minLength='30'
          placeholder='Enquiry'
          required
          spellCheck
        ></textarea>
        <button type='submit'>Send Enquiry</button>
      </form>
    </section>
  );
}

// src/components/Contact.svelte
<style>
  input,
  select,
  textarea {
    display: block;
  }
  textarea {
    resize: none;
  }
</style>

<section id="contact">
  <h2>Contact</h2>
  <p>
    <a href="mailto:stevefrenzel@gmx.de">Contact me via e-mail</a>
    or fill out the form below:
  </p>
  <form action="">
    <label for="first-name">First name:</label>
    <input
      type="text"
      name="first-name"
      id="first-name"
      placeholder="First name"
      required />
    <label for="last-name">Last name:</label>
    <input
      type="text"
      name="last-name"
      id="last-name"
      placeholder="Last name"
      required />
    <label for="company-name">Company name:</label>
    <input
      type="text"
      name="company-name"
      id="company-name"
      placeholder="Company name" />
    <label for="e-mail">E-Mail:</label>
    <input
      type="email"
      name="e-mail"
      id="e-mail"
      placeholder="E-Mail"
      required />
    <label for="enquiry">Enquiry:</label>
    <label for="select-service">Select a service:</label>
    <select name="services" id="select-service">
      <option value="generalEnquiry">General enquiry</option>
      <option value="website">Website</option>
      <option value="app">App</option>
      <option value="webVitalsCheck">Web Vitals Check</option>
    </select>
    <textarea
      id="enquiry"
      name="enquiry"
      placeholder="Enquiry"
      minlength="40"
      rows="5"
      spellcheck="true"
      required />
    <button type="submit">Send enquiry</button>
  </form>
</section>

<!-- TO DO: -->

<!-- Show minimum character count -->
<!-- Make form work -->
